language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
    - pip install autopep8
script:
    - diff <(autopep8 main.py) main.py
    - python main.py --only-abc00x
    - python main.py --only-abc00x --use-atcoder-problems
    - python main.py --only-abc00x
    - python main.py --only-abc00x --use-atcoder-problems
branches:
    only:
        - master
        - develop
